// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "@prisma/config";

// Validate required environment variables
const requiredEnvVars = ["DATABASE_URL"] as const;

for (const envVar of requiredEnvVars) {
  if (!process.env[envVar]) {
    throw new Error(
      `Missing required environment variable: ${envVar}. Please check your .env file.`
    );
  }
}

// Optional: Add database URL validation
const databaseUrl = env("DATABASE_URL");
if (databaseUrl && !databaseUrl.startsWith("postgresql://")) {
  console.warn("⚠️  DATABASE_URL format may be incorrect. Expected postgresql:// protocol.");
}


export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
